version: '2.3'

services:
  python:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    tty: true
    shm_size: '2gb'